M48
; DRILL file {KiCad (6.0.9)} date Sun Mar 19 17:38:50 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-19T17:38:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.1142Y-3.4001
X5.1142Y-4.7387
X6.4528Y-3.4001
X6.4528Y-4.7387
T0
M30
