M48
; DRILL file {KiCad 8.0.4} date 2025-07-27T14:59:46-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-27T14:59:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.1417Y-3.252
X5.1417Y-4.5906
X6.4803Y-3.252
X6.4803Y-4.5906
M30
